export const PERMISSIONS = {
  // Users & Security
  USERS_MANAGE: "users.manage",

  // Master Data & Catalog
  PRODUCTS_VIEW: "products.view",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",

  // Business Partners (Suppliers, Customers, Factories)
  PARTNERS_VIEW: "partners.view",
  PARTNERS_MANAGE: "partners.manage",

  // Inventory & Batches
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_ADJUST: "inventory.adjust",

  // Purchases
  PURCHASES_VIEW: "purchases.view",
  PURCHASES_CREATE: "purchases.create",
  PURCHASES_POST: "purchases.post",
  PURCHASES_CANCEL: "purchases.cancel",

  // Outsourced Manufacturing
  MANUFACTURING_VIEW: "manufacturing.view",
  MANUFACTURING_CREATE: "manufacturing.create",
  MANUFACTURING_UPDATE: "manufacturing.update",
  MANUFACTURING_CLOSE: "manufacturing.close",
  MANUFACTURING_CANCEL: "manufacturing.cancel",

  // Sales & Loss Prevention
  SALES_VIEW: "sales.view",
  SALES_CREATE: "sales.create",
  SALES_UPDATE: "sales.update",
  SALES_CLOSE: "sales.close",
  SALES_CANCEL: "sales.cancel",
  SALES_SELL_AT_COST: "sales.sell_at_cost",
  SALES_SELL_BELOW_COST: "sales.sell_below_cost",
  SALES_OVERRIDE_CREDIT: "sales.override_credit",

  // Financials & Treasury
  PAYMENTS_VIEW: "payments.view",
  PAYMENTS_CREATE: "payments.create",
  RECEIPTS_VIEW: "receipts.view",
  RECEIPTS_CREATE: "receipts.create",
  EXPENSES_VIEW: "expenses.view",
  EXPENSES_CREATE: "expenses.create",

  // Reports
  REPORTS_OPERATIONAL: "reports.operational",
  REPORTS_FINANCIAL: "reports.financial",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const DEFAULT_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  ADMIN: Object.values(PERMISSIONS),
  MANAGER: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE,
    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.PARTNERS_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.PURCHASES_POST,
    PERMISSIONS.PURCHASES_CANCEL,
    PERMISSIONS.MANUFACTURING_VIEW,
    PERMISSIONS.MANUFACTURING_CREATE,
    PERMISSIONS.MANUFACTURING_UPDATE,
    PERMISSIONS.MANUFACTURING_CLOSE,
    PERMISSIONS.MANUFACTURING_CANCEL,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_UPDATE,
    PERMISSIONS.SALES_CLOSE,
    PERMISSIONS.SALES_CANCEL,
    PERMISSIONS.SALES_SELL_AT_COST,
    PERMISSIONS.SALES_SELL_BELOW_COST,
    PERMISSIONS.SALES_OVERRIDE_CREDIT,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.RECEIPTS_VIEW,
    PERMISSIONS.RECEIPTS_CREATE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.REPORTS_OPERATIONAL,
    PERMISSIONS.REPORTS_FINANCIAL,
  ],
  ACCOUNTANT: [
    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.PARTNERS_MANAGE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.PURCHASES_CREATE,
    PERMISSIONS.PURCHASES_POST,
    PERMISSIONS.MANUFACTURING_VIEW,
    PERMISSIONS.MANUFACTURING_CLOSE,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CLOSE,
    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_CREATE,
    PERMISSIONS.RECEIPTS_VIEW,
    PERMISSIONS.RECEIPTS_CREATE,
    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_CREATE,
    PERMISSIONS.REPORTS_FINANCIAL,
    PERMISSIONS.REPORTS_OPERATIONAL,
  ],
  SALES: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PARTNERS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.SALES_VIEW,
    PERMISSIONS.SALES_CREATE,
    PERMISSIONS.SALES_UPDATE,
    PERMISSIONS.SALES_SELL_AT_COST,
    PERMISSIONS.RECEIPTS_VIEW,
    PERMISSIONS.RECEIPTS_CREATE,
    PERMISSIONS.REPORTS_OPERATIONAL,
  ],
  WAREHOUSE: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.PURCHASES_VIEW,
    PERMISSIONS.MANUFACTURING_VIEW,
    PERMISSIONS.REPORTS_OPERATIONAL,
  ],
  USER: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
  ],
};

export function hasPermission(
  userPermissions: string[],
  requiredPermission: PermissionCode
): boolean {
  return userPermissions.includes(requiredPermission);
}
